"""create users table

Revision ID: 148e45d76b46
Revises: f7c0fb037ef3
Create Date: 2026-05-07 19:12:29.646921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '148e45d76b46'
down_revision: Union[str, Sequence[str], None] = 'f7c0fb037ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('bed_allocation', 'allocated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('doctor_leaves', 'leave_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('doctor_leaves', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_leaves', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctor_leaves', 'leave_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('bed_allocation', 'allocated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
