"""add appointments slot information start time and end time

Revision ID: 1f5c4b8691a8
Revises: 41bf9d4ffcc4
Create Date: 2026-05-01 17:10:57.796689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f5c4b8691a8'
down_revision: Union[str, Sequence[str], None] = '41bf9d4ffcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    op.add_column('appointments', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('appointments', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('medical_records_appointment_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medical_records_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_records_pkey'))
    )
    # ### end Alembic commands ###
