"""add beds and bed_allocation

Revision ID: 41bf9d4ffcc4
Revises: 
Create Date: 2026-04-30 16:38:32.661598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bf9d4ffcc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward', sa.String(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('bed_type', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_number')
    )
    op.create_index(op.f('ix_bed_id'), 'bed', ['id'], unique=False)
    op.create_table('bed_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['bed.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_allocation_id'), 'bed_allocation', ['id'], unique=False)
    op.drop_index(op.f('idx_appointments_date'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_patient'), table_name='appointments')
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'])
    ##--------------------------------------------------------------------------------
    op.add_column('doctors', sa.Column('experience', sa.Integer(), nullable=False,server_default='0'))
    # optional cleanup
    op.alter_column('doctors', 'experience', server_default=None)
    ##-----------------------------------------------------------------
    op.drop_index(op.f('idx_lab_results_patient'), table_name='lab_results')
    op.drop_constraint(op.f('lab_results_patient_id_fkey'), 'lab_results', type_='foreignkey')
    op.create_foreign_key(None, 'lab_results', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(op.f('medications_patient_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('idx_patients_name'), table_name='patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_patients_name'), 'patients', ['name'], unique=False)
    op.drop_constraint(None, 'medications', type_='foreignkey')
    # ## Change 
    # op.drop_constraint(
    #     "medications_patient_id_fkey",
    #     "medications",
    #     type_="foreignkey"
    # )
    op.create_foreign_key(op.f('medications_patient_id_fkey'), 'medications', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.create_foreign_key(op.f('lab_results_patient_id_fkey'), 'lab_results', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_lab_results_patient'), 'lab_results', ['patient_id'], unique=False)
    op.drop_column('doctors', 'experience')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_appointments_patient'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('idx_appointments_date'), 'appointments', ['appointment_date'], unique=False)
    op.drop_index(op.f('ix_bed_allocation_id'), table_name='bed_allocation')
    op.drop_table('bed_allocation')
    op.drop_index(op.f('ix_bed_id'), table_name='bed')
    op.drop_table('bed')
    # ### end Alembic commands ###
