""" Doctor availablity coloumns available_from and available_to is added 

Revision ID: 500192fcf0ca
Revises: cd060b3869e1
Create Date: 2026-05-01 17:29:26.003045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500192fcf0ca'
down_revision: Union[str, Sequence[str], None] = 'cd060b3869e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_leaves_id'), 'doctor_leaves', ['id'], unique=False)
    op.add_column('doctors', sa.Column('available_from', sa.Time(), nullable=True))
    op.add_column('doctors', sa.Column('available_to', sa.Time(), nullable=True))
    op.add_column('doctors', sa.Column('slot_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'slot_duration')
    op.drop_column('doctors', 'available_to')
    op.drop_column('doctors', 'available_from')
    op.drop_index(op.f('ix_doctor_leaves_id'), table_name='doctor_leaves')
    op.drop_table('doctor_leaves')
    # ### end Alembic commands ###
