""" start data and end date set to NOT NULL constraint applied 

Revision ID: cd060b3869e1
Revises: 1f5c4b8691a8
Create Date: 2026-05-01 17:18:05.870605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd060b3869e1'
down_revision: Union[str, Sequence[str], None] = '1f5c4b8691a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('appointments', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
