""" doctor available_from and available_to is changed to NULL

Revision ID: f7c0fb037ef3
Revises: 500192fcf0ca
Create Date: 2026-05-01 18:04:30.614227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c0fb037ef3'
down_revision: Union[str, Sequence[str], None] = '500192fcf0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
   
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
